version: "3.8"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
    ports:
      - 8081:8081
    restart: always