server:
  port: 8091
spring:
  data:
    mongodb:
      database: productdb
      #      host: localhost
      #      port: 27017
      #      username: username
      #      password: password
  mongodb:
    embedded:
      version: 3.4.11
